[package]
name = "github_api"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
anyhow = "1.0.94"
tokio = { version = "1.42.0", features = ["full"] }
octocrab = "0.42.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
colored = "2.2.0"